-- 코드를 입력하세요
SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM ANIMAL_OUTS o
INNER JOIN ANIMAL_INS i ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact Female' AND SEX_UPON_OUTCOME LIKE 'Spayed Female'
OR SEX_UPON_INTAKE LIKE 'Intact Male' AND SEX_UPON_OUTCOME LIKE 'Neutered Male';